<?php
define("_trangchu","Home");
define("_gioithieu","About us");
define("_tintuc","News");
define("_lienhe","Contact us");
define("_motasanpham","Description");
define("_sanpham","Product");
define("_luotxem","Views");
define("_masp","Product code");
define("_ngaydang","Date Submitted");
define("_tintuckhac","Other news");
define("_hotrotructuyen","Support Online");
define("_dangonline","Online");
define("_tongtruycap","Total");
define("_diachi","Address");
define("_thongtinlienhe","Information Contact");
define("_sodienthoai","Phone");
define("_hovaten","Full name");
define("_chude","Subject");
define("_noidung","Content");
define("_matkhaumoi","New password");
define("_nhaplaimatkhaumoi","Re-new password");
define("_gui","Send");
define("_nhaplai","Reset");
define("_dangky","Sign Up");
define("_khongtimthayketqua","No results found");
define("_timduongdi","Find a way");
define("_dinhkemtaptin","Attachment file");
define("_mabaomat","Security code");
define("_dichvu","Service");
define("_timkiem","Search");
define("_capnhat","Update");
define("_boqua","Cancel");
define("_phuongxa","Wards");
define("_truycapngay","Today");
define("_dangkynhantin","Sign up to get information");
define("_quanhuyen","District");
define("_vuilongchonquanhuyen","Please select a district");
define("_soluongqualon","Quantity is not greater than 999");
define("_hoten","Full name");
define("_chitietsanpham","Product Details");
define("_xemthem","View more");
define("_tuyendung","Recruitment");
define("_gia","Price");
define("_thongtincanhan","Information personal");
define("_thuvienanh","Album");
define("_sanphamnoibat","Featured products");
define("_ketquatimkiem","Search results");
define("_dathang","Add to cart");
define("_matkhaucu","Old password");
define("_giohang","My cart");
define("_hinh","Picture");
define("_soluong","Number");
define("_thanhtien","Amount");
define("_tinhthanh","City");
define("_nhaptukhoatimkiem","Enter the keyword...");
define("_tinhtrang","Status");
define("_hethang","Out of stock");
define("_dangcapnhat","Updating");
define("_danhmucsanpham","Product portfolio");
define("_trongtuan","Week");
define("_thaydoimatkhau","Change password");
define("_thongketruycap","Statistical access");
define("_thongtinsanpham","Products Information");
define("_vuilongchonphuongxa","Please select a ward");
define("_traloi","Answer");
define("_huy","Cancel");
define("_binhluanve","comments about");
define("_moibanthaoluan","Please discuss. Please enter Vietnamese accented, minimum 10 characters.");
define("_co","Have");
define("_danhgia","Review");
define("_xacnhan","Confirm");
define("_sanphamcungloai","Product Similar");
define("_conhang","Stocking");
define("_thanhtoan","Pay");
define("_chonvideo","Choose video");
define("_slogandangkynhantin","Leave information to receive the latest news from us");
define("_giamoi","New price");
define("_giacu","Old price");
define("_binhluan","Comment");
define("_baivietkhac","Other news");
define("_banmuonxoasanphamnay","Do you want to remove this product from your shopping cart?");
define("_soluongkhongnhohonkhong","Order quantity must not be less than 0");
define("_muatiep","Buy more");
define("_xoatatca","Delete all");
define("_kichthuoc","Size");
define("_dangnhap","Login");
define("_taikhoan","Username");
define("_matkhau","Password");
define("_nhomatkhau","Remember password");
define("_quenmatkhau","Forget password");
define("_nhaplaimatkhau","Confirm password");
define("_dienthoai","Phone");
define("_banchuacotaikhoan","You don't have a account");
define("_laymatkhau","Get password");
define("_apdung","Apply");
define("_phivanchuyen"," Transport fee");
define("_tamtinh","Provisional");
define("_tongtien","Total price");
define("_map","Map");
define("_donhang","Order");
define("_lichsudonhang","Order history");
define("_trangdau","First page");
define("_trangcuoi","Last page");
define("_trangbantruycapkhongtontai","The page you visited does not exist.");
define("_vetrangchu","Back to homepage");
define("_chiase","Share");
define("_nhapmauudai","Enter the promotion code");
define("_xoa","Delete");
define("_mausac","Color");
define("_thongtingiaohang","Shipment Details");
define("_vuilongchontinhthanh","Please select a province");
define("_yeucaukhac","Other (Optional)");
define("_khongtontaisanphamtronggiohang","No products in your shopping cart !");
define("_chuanhapmauudai"," Did not enter the promotion code");
define("_giohangcuaban","Your cart");
define("_vuilongchonsizevamau","Please select size and color !");
define("_dangkytaiday","Sign up here");
define("_nhaphoten","Enter your full name");
define("_nhaptaikhoan","Enter your account");
define("_nhapmatkhau","Choose password (5-15 chars)");
define("_nhapemail","Enter your email address");
define("_nhapdienthoai","Enter your number phone");
define("_nhapdiachi","Enter your address");
define("_nhapngaysinh","Enter your birthday");
define("_gioitinh","Gender");
define("_nam","Male");
define("_nu","Female");
define("_kichhoat","Active");
define("_nhapmakichhoat","Enter your active code");
define("_nhapmatkhaucu","Enter old password");
define("_nhapmatkhaumoi","Enter new password");
define("_thich","Like");
define("_dathich","Liked");
define("_taithembinhluan","Get more comments");
define("_trangke","Next page");
define("_trangtruoc","Prev page");
define("_hinhanh","Image");
define("_tensanpham","Product name");
define("_duong","Street");
define("_hinhthucthanhtoan","Payments");
define("_vuilongnhaphoten","Please enter your first and last name");
define("_vuilongnhapsodienthoai","Please enter the phone number");
define("_vuilongnhapdiachi","Please enter your address");
define("_vuilongnhapdiachiemail","Please enter email address");
define("_vuilongnhapchude","Please enter subject");
define("_vuilongnhapnoidung","Please enter content");
define("_chon","Choose");
define("_tieptucmuahang","Continue shopping");
define("_trongthang","Month");
define("_chinhsach","Supporting policies");
define("_thuonghieu","Brand");
define("_uudai","Promotion");
define("_chuacouudai","No offers yet");
define("_mauudaidahethan","Promotion code has expired");
define("_mauudaidaduocsudunghoackhongtontai","The promotion code has been used or does not exist");
define("_vuilongnhaptaikhoan","Please enter an account");
define("_vuilongnhapmatkhau","Please enter a password");
define("_vuilongnhaplaimatkhau","Please enter the password again");
define("_vuilongnhapngaysinh","Please enter your birthday");
define("_ngaysinh","Date of birth");
define("_vuilongnhapmakichhoat","Please enter the activation code");
define("_dangxuat","Logout");
define("_homnay","Today");
define("_homqua","Yesterday");
define("_thongbao","Notify");
define("_thoat","Exit");
define("_chuanhaptukhoatimkiem","No search keywords entered");
?>