<?php
define("_trangchu","Trang chủ");
define("_gioithieu","Giới thiệu");
define("_tintuc","Tin tức");
define("_lienhe","Liên hệ");
define("_motasanpham","Mô tả");
define("_sanpham","Sản phẩm");
define("_luotxem","Lượt xem");
define("_masp","Mã sản phẩm");
define("_ngaydang","Ngày đăng");
define("_tintuckhac","Tin tức khác");
define("_hotrotructuyen","Hổ trợ trực tuyến");
define("_dangonline","Đang online");
define("_tongtruycap","Tổng truy cập");
define("_diachi","Địa chỉ");
define("_thongtinlienhe","Thông tin liên hệ");
define("_sodienthoai","Số điện thoại");
define("_hovaten","Họ và tên");
define("_chude","Chủ đề");
define("_noidung","Nội dung");
define("_matkhaumoi","Mật khẩu mới");
define("_nhaplaimatkhaumoi","Nhập lại mật khẩu mới");
define("_gui","Gửi");
define("_nhaplai","Nhập lại");
define("_dangky","Đăng ký");
define("_khongtimthayketqua","Không tìm thấy kết quả");
define("_timduongdi","Tìm đường đi");
define("_dinhkemtaptin","Đính kèm file");
define("_mabaomat","Mã bảo mật");
define("_dichvu","Dịch vụ");
define("_timkiem","Tìm kiếm");
define("_capnhat","Cập nhật");
define("_boqua","Bỏ qua");
define("_phuongxa","Phường/xã");
define("_truycapngay","Truy cập ngày");
define("_dangkynhantin","Đăng ký nhận tin");
define("_quanhuyen","Quận/huyện");
define("_vuilongchonquanhuyen","Vui lòng chọn quận huyện");
define("_soluongqualon","Số lượng không được lớn hơn 999");
define("_hoten","Họ tên");
define("_chitietsanpham","Chi tiết sản phẩm");
define("_xemthem","Xem thêm");
define("_tuyendung","Tuyển dụng");
define("_gia","Giá");
define("_thongtincanhan","Thông tin cá nhân");
define("_thuvienanh","Thư viện ảnh");
define("_sanphamnoibat","Sản phẩm nổi bật");
define("_ketquatimkiem","Kết quả tìm kiếm");
define("_dathang","Đặt hàng");
define("_matkhaucu","Mật khẩu cũ");
define("_giohang","Giỏ hàng");
define("_hinh","Hình");
define("_soluong","Số lượng");
define("_thanhtien","Thành tiền");
define("_tinhthanh","Tỉnh/thành phố");
define("_nhaptukhoatimkiem","Nhập từ khóa cần tìm...");
define("_tinhtrang","Tình trạng");
define("_hethang","Hết hàng");
define("_dangcapnhat","Đang cập nhật");
define("_danhmucsanpham","Danh mục sản phẩm");
define("_trongtuan","Tuần");
define("_thaydoimatkhau","Thay đổi mật khẩu");
define("_thongketruycap","Thống kê truy cập");
define("_thongtinsanpham","Thông tin sản phẩm");
define("_vuilongchonphuongxa","Vui lòng chọn phường xã");
define("_traloi","Trả lời");
define("_huy","Hủy");
define("_binhluanve","bình luận về");
define("_moibanthaoluan","Mời bạn thảo luận. Vui lòng nhập Tiếng Việt có dấu, tối thiểu 10 ký tự.");
define("_co","Có");
define("_danhgia","Đánh giá");
define("_xacnhan","Xác nhận");
define("_sanphamcungloai","Sản phẩm cùng loại");
define("_conhang","Còn hàng");
define("_thanhtoan","Thanh toán");
define("_chonvideo","Chọn video");
define("_slogandangkynhantin","Để lại thông tin để nhận tin tức mới nhất từ chúng tôi");
define("_giamoi","Giá mới");
define("_giacu","Giá cũ");
define("_binhluan","Bình luận");
define("_baivietkhac","Bài viết khác");
define("_banmuonxoasanphamnay","Bạn muốn xóa sản phẩm này khỏi giỏ hàng ? ");
define("_soluongkhongnhohonkhong","Số lượng đặt mua không được nhỏ hơn 0");
define("_muatiep","Mua tiếp");
define("_xoatatca","Xóa tất cả");
define("_kichthuoc","Kích thước");
define("_dangnhap","Đăng nhập");
define("_taikhoan","Tài khoản");
define("_matkhau","Mật khẩu");
define("_nhomatkhau","Nhớ mật khẩu");
define("_quenmatkhau","Quên mật khẩu");
define("_nhaplaimatkhau","Nhập lại mật khẩu");
define("_dienthoai","Điện thoại");
define("_banchuacotaikhoan","Bạn chưa có tài khoản ");
define("_laymatkhau","Lấy mật khẩu");
define("_apdung","Áp dụng");
define("_phivanchuyen","Phí vận chuyển");
define("_tamtinh","Tạm tính");
define("_tongtien","Tổng tiền");
define("_map","Bản đồ");
define("_donhang","Đơn hàng");
define("_lichsudonhang","Lịch sử đơn hàng");
define("_trangdau","Trang đầu");
define("_trangcuoi","Trang cuối");
define("_trangbantruycapkhongtontai","Trang bạn truy cập không tồn tại.");
define("_vetrangchu","Về trang chủ");
define("_chiase","Chia sẻ");
define("_nhapmauudai","Nhập mã ưu đãi");
define("_xoa","Xóa");
define("_mausac","Màu sắc");
define("_thongtingiaohang","Thông tin giao hàng");
define("_vuilongchontinhthanh","Vui lòng chọn tỉnh thành");
define("_yeucaukhac","Yêu cầu khác (không bắt buộc)");
define("_khongtontaisanphamtronggiohang","Không tồn tại sản phẩm nào trong giỏ hàng !");
define("_chuanhapmauudai","Chưa nhập mã ưu đãi");
define("_giohangcuaban","Giỏ hàng của bạn");
define("_vuilongchonsizevamau","Vui lòng chọn size và màu !");
define("_dangkytaiday","Đăng ký");
define("_nhaphoten","Nhập họ tên của bạn");
define("_nhaptaikhoan","Nhập tài khoản của bạn");
define("_nhapmatkhau","Nhập mật khẩu (5-15 ký tự)");
define("_nhapemail","Nhập địa chỉ email của bạn");
define("_nhapdienthoai","Nhập số điện thoại");
define("_nhapdiachi","Nhập địa chỉ của bạn");
define("_nhapngaysinh","Nhập ngày sinh");
define("_gioitinh","Giới tính");
define("_nam","Nam");
define("_nu","Nữ");
define("_kichhoat","Kích hoạt");
define("_nhapmakichhoat","Nhập mã kích hoạt");
define("_nhapmatkhaucu","Nhập mật khẩu cũ");
define("_nhapmatkhaumoi","Nhập mật khẩu mới");
define("_thich","Thích");
define("_dathich","Đã thích");
define("_taithembinhluan","Tải thêm bình luận");
define("_trangke","Trang kế");
define("_trangtruoc","Trang trước");
define("_hinhanh","Hình ảnh");
define("_tensanpham","Tên sản phẩm");
define("_duong","Đường phố");
define("_hinhthucthanhtoan","Hình thức thanh toán");
define("_vuilongnhaphoten","Vui lòng nhập họ và tên");
define("_vuilongnhapsodienthoai","Vui lòng nhập số điện thoại");
define("_vuilongnhapdiachi","Vui lòng nhập địa chỉ");
define("_vuilongnhapdiachiemail","Vui lòng nhập địa chỉ email");
define("_vuilongnhapchude","Vui lòng nhập chủ đề");
define("_vuilongnhapnoidung","Vui lòng nhập nội dung");
define("_chon","Chọn");
define("_tieptucmuahang","Tiếp tục mua hàng");
define("_trongthang","Tháng");
define("_chinhsach","Chính sách hỗ trợ");
define("_thuonghieu","Thương hiệu");
define("_uudai","Ưu đãi");
define("_chuacouudai","Chưa có ưu đãi");
define("_mauudaidahethan","Mã ưu đãi đã hết hạng");
define("_mauudaidaduocsudunghoackhongtontai","Mã ưu đãi đã được sử dụng hoặc không tồn tại");
define("_vuilongnhaptaikhoan","Vui lòng nhập tài khoản");
define("_vuilongnhapmatkhau","Vui lòng nhập mật khẩu");
define("_vuilongnhaplaimatkhau","Vui lòng nhập lại mật khẩu");
define("_vuilongnhapngaysinh","Vui lòng nhập ngày sinh");
define("_ngaysinh","Ngày sinh");
define("_vuilongnhapmakichhoat","Vui lòng nhập mã kích hoạt");
define("_dangxuat","Đăng xuất");
define("_homnay","Hôm nay");
define("_homqua","Hôm qua");
define("_thongbao","Thông báo");
define("_thoat","Thoát");
define("_chuanhaptukhoatimkiem","Chưa nhập từ khóa tìm kiếm");
?>